### ISSUE TITLE
Where to get a more complete database?

### ISSUE THREAD

**Issue by sam0x17** [robo9k/rust-magic#22]
It looks like by default no databases are included. Where can I find more? Specifically I am looking for something that has most image types, but googling around has yielded nothing.

**Comment by robo9k** [comment]
You can find some documentation if you have the man pages for `libmagic`/`file` installed locally or online, e.g.
* `man 3 libmagic`, `magic_load` is what corresponds to `magic::Cookie::load`
* `man 4 magic` has details on the magic database file format itself

Note that the little Rust dance with `Cookie::open(..)` and then `cookie.load(..)` is close to what you'd have to do if you were using the `libmagic` C library from C (`magic_open(..)`, `magic_load(..)`).

You should get both the man pages and the default database with your `libmagic`/`file` installation. If you're lucky the installed man pages will even mention the exact paths of the default database on your system.
Newer versions of the `libmagic` C library have functions to determine the path of the default database (`magic_getpath(..)`), but that functionality is not currently available in the `magic` Rust crate.

Coming back to your original issue: I'm not aware of additional magic databases for image types, but I believe the default magic database that's shipped with `libmagic`/`file` should have you covered.

Does loading the default database solve your issue?
Where would you have expected documentation about the default database in the `rust-magic` project?

**Comment by sam0x17** [comment]
Thanks for the info. I think it might make sense to include a blurb about this in the main README.md page and to alter the example code to load an example local path with a comment specifying that this is the path for your system, but it could vary and maybe with a link to a thorough description like what you posted above.

A lot of people coming to this project will have never used libmagic before so will help them out to make this more clear

**Comment by robo9k** [comment]
Hej @sam0x17 !

I've added some details about the inner workings of `libmagic` to the crate docs, as can be seen on e.g. the [docs.rs for `magic` 0.13.0-alpha.3](https://docs.rs/magic/0.13.0-alpha.3/magic/)
Would appreciate if you could take a look :)

I'm still not happy with the API around loading the default database, but as can be seen in #6 this is a long-standing issue which I intend to fix in a later version as well as more documentation and examples in general.

I think your issue with loading a (default) database should be solved by the new documentation. If so we could close this issue here?

**Comment by sam0x17** [comment]
This looks great, thanks!
